### PR TITLE
Fix NPM Audit Detected Issues

### PR DESCRIPTION
**Pull request by AdrianHL**
Before

```
                       === npm audit security report ===         

...

found 768 vulnerabilities (758 low, 2 moderate, 8 high) in 1367 scanned packages
  run `npm audit fix` to fix 757 of them.
  2 vulnerabilities require semver-major dependency updates.
  9 vulnerabilities require manual review. See the full report for details.
```

After

```                                                     
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 1472 scanned packages

```

Happy Hackotoberfest

### CODE REVIEW

**Comment by AdrianHL** [comment]
Can you please add "hacktoberfest" to repository labels? In this case i will earn a point for helping open source projects :)

**Comment by rickwest** [comment]
> Can you please add "hacktoberfe

The repository does have this label. Are you having issues with your contributions not showing up?

Cheers, Rick

**Comment by AdrianHL** [comment]
Yes, it looks like the label is a bit different.

image

legend says ....

image

So it looks like it has to be exactly `hacktoberfest`.

Thanks in advance

**Comment by rickwest** [comment]
Ah...typo! Should be sorted now, let me know if that's fixed for you

**Comment by AdrianHL** [comment]
Yes, it has been sorted automatically. Thanks.

**Pull request merged**
